server:
  shutdown: graceful

spring:
  application:
    name: oo-exam
  datasource:
    url: jdbc:h2:mem:exam;MODE=LEGACY;
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
  lifecycle:
    timeout-per-shutdown-phase: 1m

logging:
  level:
    org:
      springframework:
        jdbc:
          core:
            JdbcTemplate: debug
            StatementCreatorUtils: trace